Siganushka\ProductBundle\Entity\Product:
    attributes:
        id:
            groups: ['product:item', 'product:collection']
        name:
            groups: ['product:item', 'product:collection']
        description:
            groups: ['product:item', 'product:collection']
        img:
            groups: ['product:item', 'product:collection']
        options:
            groups: ['product:item', 'product:collection']
        variants:
            groups: ['product:item', 'product:collection']
        createdAt:
            groups: ['product:item', 'product:collection']
        updatedAt:
            groups: ['product:item', 'product:collection']
