Siganushka\ProductBundle\Entity\ProductOption:
    attributes:
        id:
            groups: ['product_option:item', 'product:item', 'product:collection']
        name:
            groups: ['product_option:item', 'product:item', 'product:collection']
        values:
            groups: ['product_option:item', 'product:item', 'product:collection']
        createdAt:
            groups: ['product_option:item', 'product:item', 'product:collection']
        updatedAt:
            groups: ['product_option:item', 'product:item', 'product:collection']
