Siganushka\ProductBundle\Entity\Product:
    attributes:
        img:
            groups: ['item', 'collection']
        options:
            groups: ['item', 'collection']
        variants:
            groups: ['item', 'collection']

Siganushka\ProductBundle\Entity\ProductOption:
    attributes:
        values:
            groups: ['item', 'collection']

Siganushka\ProductBundle\Entity\ProductOptionValue:
    attributes:
        img:
            groups: ['item', 'collection']

Siganushka\ProductBundle\Entity\ProductVariant:
    attributes:
        img:
            groups: ['item', 'collection']
